# Generated by Django 4.1.5 on 2023-01-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin_or_hod_login_credentials',
            fields=[
                ('usernames', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('passwords', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='faculty_login_credentials',
            fields=[
                ('usernames', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('passwords', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='students_login_credentials',
            fields=[
                ('usernames', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('passwords', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
