# Generated by Django 4.1.5 on 2023-01-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_or_hod_login_credentials',
            old_name='passwords',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='admin_or_hod_login_credentials',
            old_name='usernames',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='faculty_login_credentials',
            old_name='passwords',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='faculty_login_credentials',
            old_name='usernames',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='students_login_credentials',
            old_name='passwords',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='students_login_credentials',
            old_name='usernames',
            new_name='username',
        ),
    ]
