# Generated by Django 4.0.6 on 2023-01-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginPage', '0002_rename_passwords_admin_or_hod_login_credentials_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[(1, 'HOD'), (2, 'Staff'), (3, 'Student')], max_length=255)),
                ('profile_pic', models.FileField(upload_to='media/profile_pic')),
            ],
        ),
        migrations.AlterField(
            model_name='admin_or_hod_login_credentials',
            name='username',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='faculty_login_credentials',
            name='username',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='students_login_credentials',
            name='username',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
