# Generated by Django 4.0.6 on 2023-01-23 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemApp', '0003_alter_customuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('H', 'HOD'), ('F', 'Faculty'), ('S', 'STUDENT')], max_length=50),
        ),
    ]
