# Generated by Django 4.0.6 on 2023-01-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SystemApp', '0004_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'HOD'), ('2', 'Faculty'), ('3', 'STUDENT')], max_length=50),
        ),
    ]
